# image: https://hub.docker.com/r/tuxgasy/dolibarr
# docs: https://github.com/tuxgasy/docker-dolibarr

version: '3.8'

services:
    mariadb:
        image: mariadb:${DB_MARIADB_VERSION}
        container_name: ${APP_NAME}-mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_MARIADB_PASSWORD}
            MYSQL_DATABASE: ${DB_MARIADB_NAME}
            MYSQL_USER: ${DB_MARIADB_USER}
            MARIADB_PASSWORD: ${DB_MARIADB_PASSWORD}
        volumes:
            - mariadb:/var/lib/mysql

    dolibarr:
        image: tuxgasy/dolibarr:${APP_VERSION}
        container_name: ${APP_NAME}
        restart: always
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: ${DB_MARIADB_USER}
            DOLI_DB_PASSWORD: ${DB_MARIADB_PASSWORD}
            DOLI_DB_NAME: ${DB_MARIADB_NAME}
            DOLI_ADMIN_LOGIN: ${APP_USER}
            DOLI_ADMIN_PASSWORD: ${APP_PASSWORD}
            DOLI_URL_ROOT: 'http://0.0.0.0'
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
            PHP_INI_MEMORY_LIMIT: 512M
            DOLI_AUTH: dolibarr
        ports:
            - "${APP_HTTP_PORT}:80"
        volumes:
            - dolibarr_html:/var/www/html
            - dolibarr_documents:/var/www/documents
        links:
            - mariadb
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mariadb:
  dolibarr_html:
  dolibarr_documents:
